### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by houd1ni** [dimitrinicolas/marmottajax#13]
~~- [ ]Create tests, using this: http://jasmine.github.io/2.0/ajax.html~~
(Aren't more effective than those in `/Samples`. Just update them.)
- [x]  How about gitter?

*

- [ ]  Cache handling
- [ ]  Improve docs, make them on different pages, with useful structure
- [ ]  Multifile upload
- [ ]  Data + files boundle
- [ ]  Run some callback just before
- [ ]  Run some callback while a part is loaded
- [ ]  Run some callback if some timeout expired
- [ ]  Code review, refactor, improve  minify-ready
- [ ]  Adapters for different input data. E.g. jQuery's formats of $.ajax and, maybe aliases-shortcuts
- [ ]  Different builds for different purposes
- [ ]  WebSockets adaptation
- [ ] Show it to the World

**Comment by houd1ni** [comment]
For others: The roadmap is moved in the branch.
This, master branch, will be maintained and found bugs will be closed, but major features will be created in the branch.
